// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EngineeringCourses int32

const (
	EngineeringCourses_COMPUTER_ENG      EngineeringCourses = 0
	EngineeringCourses_CHEMICAL_ENG      EngineeringCourses = 1
	EngineeringCourses_CIVIL_ENG         EngineeringCourses = 2
	EngineeringCourses_ELECTRICAL_ENG    EngineeringCourses = 3
	EngineeringCourses_MECHANICAL_ENG    EngineeringCourses = 4
	EngineeringCourses_PETROCHEMICAL_ENG EngineeringCourses = 5
	EngineeringCourses_META_ENG          EngineeringCourses = 6
)

// Enum value maps for EngineeringCourses.
var (
	EngineeringCourses_name = map[int32]string{
		0: "COMPUTER_ENG",
		1: "CHEMICAL_ENG",
		2: "CIVIL_ENG",
		3: "ELECTRICAL_ENG",
		4: "MECHANICAL_ENG",
		5: "PETROCHEMICAL_ENG",
		6: "META_ENG",
	}
	EngineeringCourses_value = map[string]int32{
		"COMPUTER_ENG":      0,
		"CHEMICAL_ENG":      1,
		"CIVIL_ENG":         2,
		"ELECTRICAL_ENG":    3,
		"MECHANICAL_ENG":    4,
		"PETROCHEMICAL_ENG": 5,
		"META_ENG":          6,
	}
)

func (x EngineeringCourses) Enum() *EngineeringCourses {
	p := new(EngineeringCourses)
	*p = x
	return p
}

func (x EngineeringCourses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineeringCourses) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (EngineeringCourses) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x EngineeringCourses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineeringCourses.Descriptor instead.
func (EngineeringCourses) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type DiplomaCourses int32

const (
	DiplomaCourses_COMPUTER_DIP      DiplomaCourses = 0
	DiplomaCourses_CHEMICAL_DIP      DiplomaCourses = 1
	DiplomaCourses_CIVIL_DIP         DiplomaCourses = 2
	DiplomaCourses_ELECTRICAL_DIP    DiplomaCourses = 3
	DiplomaCourses_MECHANICAL_DIP    DiplomaCourses = 4
	DiplomaCourses_PETROCHEMICAL_DIP DiplomaCourses = 5
	DiplomaCourses_META_DIP          DiplomaCourses = 6
)

// Enum value maps for DiplomaCourses.
var (
	DiplomaCourses_name = map[int32]string{
		0: "COMPUTER_DIP",
		1: "CHEMICAL_DIP",
		2: "CIVIL_DIP",
		3: "ELECTRICAL_DIP",
		4: "MECHANICAL_DIP",
		5: "PETROCHEMICAL_DIP",
		6: "META_DIP",
	}
	DiplomaCourses_value = map[string]int32{
		"COMPUTER_DIP":      0,
		"CHEMICAL_DIP":      1,
		"CIVIL_DIP":         2,
		"ELECTRICAL_DIP":    3,
		"MECHANICAL_DIP":    4,
		"PETROCHEMICAL_DIP": 5,
		"META_DIP":          6,
	}
)

func (x DiplomaCourses) Enum() *DiplomaCourses {
	p := new(DiplomaCourses)
	*p = x
	return p
}

func (x DiplomaCourses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiplomaCourses) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (DiplomaCourses) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x DiplomaCourses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiplomaCourses.Descriptor instead.
func (DiplomaCourses) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type MedicalCourses int32

const (
	MedicalCourses_MBBS_MED    MedicalCourses = 0
	MedicalCourses_BPT_MED     MedicalCourses = 1
	MedicalCourses_BSC_MED     MedicalCourses = 2
	MedicalCourses_NURSING_MED MedicalCourses = 3
	MedicalCourses_BDS_MED     MedicalCourses = 4
	MedicalCourses_BHMS_MDS    MedicalCourses = 5
)

// Enum value maps for MedicalCourses.
var (
	MedicalCourses_name = map[int32]string{
		0: "MBBS_MED",
		1: "BPT_MED",
		2: "BSC_MED",
		3: "NURSING_MED",
		4: "BDS_MED",
		5: "BHMS_MDS",
	}
	MedicalCourses_value = map[string]int32{
		"MBBS_MED":    0,
		"BPT_MED":     1,
		"BSC_MED":     2,
		"NURSING_MED": 3,
		"BDS_MED":     4,
		"BHMS_MDS":    5,
	}
)

func (x MedicalCourses) Enum() *MedicalCourses {
	p := new(MedicalCourses)
	*p = x
	return p
}

func (x MedicalCourses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MedicalCourses) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (MedicalCourses) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x MedicalCourses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MedicalCourses.Descriptor instead.
func (MedicalCourses) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type Distance int32

const (
	Distance_NEARBY     Distance = 0
	Distance_MID_RANGE  Distance = 2
	Distance_LONG_RANGE Distance = 3
)

// Enum value maps for Distance.
var (
	Distance_name = map[int32]string{
		0: "NEARBY",
		2: "MID_RANGE",
		3: "LONG_RANGE",
	}
	Distance_value = map[string]int32{
		"NEARBY":     0,
		"MID_RANGE":  2,
		"LONG_RANGE": 3,
	}
)

func (x Distance) Enum() *Distance {
	p := new(Distance)
	*p = x
	return p
}

func (x Distance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Distance) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (Distance) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x Distance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Distance.Descriptor instead.
func (Distance) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude float32 `protobuf:"fixed32,7,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude  float32 `protobuf:"fixed32,8,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44,
	0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x2a, 0x94, 0x01, 0x0a, 0x12, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x43,
	0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x52, 0x5f, 0x45, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x43, 0x48, 0x45, 0x4d, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x43, 0x49, 0x56, 0x49, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x12,
	0x0a, 0x0e, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x52, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47,
	0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x45, 0x43, 0x48, 0x41, 0x4e, 0x49, 0x43, 0x41, 0x4c,
	0x5f, 0x45, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x45, 0x54, 0x52, 0x4f, 0x43,
	0x48, 0x45, 0x4d, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x0c, 0x0a,
	0x08, 0x4d, 0x45, 0x54, 0x41, 0x5f, 0x45, 0x4e, 0x47, 0x10, 0x06, 0x2a, 0x90, 0x01, 0x0a, 0x0e,
	0x44, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x52, 0x5f, 0x44, 0x49, 0x50, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x43, 0x48, 0x45, 0x4d, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x44, 0x49, 0x50,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x49, 0x56, 0x49, 0x4c, 0x5f, 0x44, 0x49, 0x50, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x52, 0x49, 0x43, 0x41, 0x4c, 0x5f,
	0x44, 0x49, 0x50, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x45, 0x43, 0x48, 0x41, 0x4e, 0x49,
	0x43, 0x41, 0x4c, 0x5f, 0x44, 0x49, 0x50, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x45, 0x54,
	0x52, 0x4f, 0x43, 0x48, 0x45, 0x4d, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x44, 0x49, 0x50, 0x10, 0x05,
	0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x45, 0x54, 0x41, 0x5f, 0x44, 0x49, 0x50, 0x10, 0x06, 0x2a, 0x64,
	0x0a, 0x0e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x42, 0x42, 0x53, 0x5f, 0x4d, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x42, 0x50, 0x54, 0x5f, 0x4d, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42,
	0x53, 0x43, 0x5f, 0x4d, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x55, 0x52, 0x53,
	0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x44, 0x53,
	0x5f, 0x4d, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x48, 0x4d, 0x53, 0x5f, 0x4d,
	0x44, 0x53, 0x10, 0x05, 0x2a, 0x35, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x45, 0x41, 0x52, 0x42, 0x59, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x4d, 0x49, 0x44, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c,
	0x4f, 0x4e, 0x47, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x03, 0x42, 0x3f, 0x0a, 0x35, 0x63,
	0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []interface{}{
	(EngineeringCourses)(0), // 0: EngineeringCourses
	(DiplomaCourses)(0),     // 1: DiplomaCourses
	(MedicalCourses)(0),     // 2: MedicalCourses
	(Distance)(0),           // 3: Distance
	(*Location)(nil),        // 4: Location
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
